[terminal.shell]
program = "/bin/bash"

[window]
opacity = 0.8
decorations = "None"
title = "terminal"
dynamic_title = false
[scrolling]
history = 5000
multiplier = 2

[colors]
[colors.primary]
background = "#201d2a"
foreground = "#9992b0"

[colors.cursor]
cursor = "#b042ff"

[colors.normal]
black = "#201d2a"
red = "#9375f5"
green = "#d294ff"
yellow = "#ecd1ff"
blue = "#a286fd"
magenta = "#d294ff"
cyan = "#b5a0fe"
white = "#9992b0"

[colors.bright]
black = "#625a7c"
red = "#dba8ff"
green = "#2c2839"
yellow = "#4b455f"
blue = "#6e658b"
magenta = "#dcd2fe"
cyan = "#ca80ff"
white = "#efebff"

